### ISSUE TITLE
如果要结合blade，smarty，twig 之类的模板引擎使用view组件，是否要启用swoole的一键协程

### ISSUE THREAD

**Issue by slince** [hyperf/view#1]
如果要结合`blade`，`smarty`，`twig` 之类的模板引擎使用`view`组件，是否要启用`swoole`的一键协程

https://github.com/smarty-php/smarty/blob/c9f0de05f41b9e52798b268ab1e625fac3b8578c/libs/sysplugins/smarty_internal_resource_stream.php#L53

https://github.com/twigphp/Twig/blob/d073fed7f1979689a25d161423c90ecccaf87c4f/src/Loader/FilesystemLoader.php#L145

如上述的代码，这些模板引擎在加载模板文件的时候均使用的是php原生的io函数，是否会对协程产生影响

**Comment by limingxinleo** [comment]
所以要结合 Task 使用，并且不开启 Task协程。

另外，Issue 都提到 https://github.com/hyperf/hyperf

**Comment by slince** [comment]
@limingxinleo   那你们应该把这个仓库的issue关了
